---
title: "Emacs Speaks Statistics -- Introductions"
output: github_document
---

## About

The _ESS Introductions_ regroup several introductory presentation videos and
support vignettes or files. It is _work in progress_ so please revisit frequently.

## Current Status

All the videos are available on the [YouTube
Channel](https://www.youtube.com/channel/UCph8LPTQ8gkNnKf1WHF2Tgg/featured).

| <span>Title</span>        | <span>Author</span>                                                                                                                                                       | <span>Video Link</span>                   | <span>Support Material</span>                                                                                                                                                                                                         | <span>Repository</span>                                              |
| :-----------------------  | :-----------------------------------------------------                                                                                                                    | :---------------------------------------- | ---------------------------------------------------------------------------------------------                                                                                                                                         | ---------------------------------------------------------------      |
| First Steps with Emacs    | [Dirk Eddelbuettel](https://github.com/eddelbuettel)                                                                                                                      | [YouTube](https://youtu.be/1YOrd7NCGkg)   | [PDF Slides](https://github.com/ess-intro/presentation-first-steps/blob/master/first-steps.pdf)                                                                                                                                       | [Repo](https://github.com/ess-intro/presentation-first-steps)        |
| Installing ESS            | [Tyler Smith](https://github.com/plantarum)                                                                                                                               | [YouTube](https://youtu.be/So1LYzSk9o0)   |                                                                                                                                                                                                                                       | [Repo]()                                                             |
| ESS with Spacemacs        | [Alexander Zarebski](https://github.com/aezarebski)                                                                                                                       | [YouTube](https://youtu.be/P6O1s2XHphI)   | [PDF Slides](https://github.com/ess-intro/presentation-ess-from-spacemacs/raw/main/presentation/slides.pdf), [Quickstart guide](https://github.com/ess-intro/presentation-ess-from-spacemacs/blob/main/presentation/README.org)       | [Repo](https://github.com/ess-intro/presentation-ess-from-spacemacs) |
| ESS Customization         | [Frédéric Santos](https://github.com/frederic-santos)                                                                                                                     | [YouTube](https://youtu.be/Lf8qrLuvYp8)   | [PDF Tutorial](https://github.com/ess-intro/presentation-ess-customization/blob/main/tutorial/ess-customization.pdf), [Emacs ess-init.el](https://github.com/ess-intro/presentation-ess-customization/blob/main/tutorial/ess-init.el) | [Repo](https://github.com/ess-intro/presentation-ess-customization)  |
| ESS and OrgMode           | [Greg Minshall](https://github.com/greg-minshall)                                                                                                                         | [YouTube](https://youtu.be/BbZbtgvwrI8)   | [PDF Slides](https://ess-intro.github.io/presentation-org-mode/artefacts/ess-org-beamer.pdf)                                                                                                                                          | [Repo](https://github.com/ess-intro/presentation-org-mode)           |
| Multi-User via Byobu/Tmux | [Dirk Eddelbuettel](https://github.com/eddelbuettel), [Grant McDermott](https://github.com/grantmcdermott), [Vincent Arel-Bundock](https://github.com/vincentarelbundock) | [YouTube](https://youtu.be/JX9m5B0BL7s)   | [PDF Slides](https://github.com/ess-intro/presentation-multi-user/blob/master/multi-user.pdf)                                                                                                                                         | [Repo](https://github.com/ess-intro/presentation-multi-user)         |




## Repositories

See [the GitHub organisation ess-intro](https://github.com/ess-intro) is where
it all happens.

## Wiki

The [wiki of the ess-intro repo](https://github.com/ess-intro/ess-intro/wiki) is
a good starting point for additional information.

## Feedback and getting in touch

If you have suggestions or questions about a particular presentation, please
feel free to open an issue in the repository. Or if you have some meta
information about the presentations, you can open an issue in the [ESS intros
project's repository](https://github.com/ess-intro/ess-intro/issues). Finally,
if you are looking for generic help with ESS (and can't find a solution in the
[documentation](http://ess.r-project.org/Manual/ess.html)), you can sign up for
the ESS Discussion and Help mailing list
[here](https://stat.ethz.ch/mailman/listinfo/ess-help).

## Copyright

All material is copyright by their respective creators.

## License

We strive to have all material available under approved Open Source licenses.
Contributors can choose their licensing terms provided these fit the overall
guideline.




